### ISSUE TITLE
Decide the design of the countdown clock

### ISSUE THREAD

**Issue by riotanabe** [UQdeco2800/2022-ext-studio-1#6] opened 2022-08-14 15:10 UTC

**Comment by Connor-Ryan-1998** [comment] 2022-08-20 02:09
Duplicate of #5

**Closed by Connor-Ryan-1998** 2022-08-20 02:09 UTC

**Comment by riotanabe** [comment] 2022-08-20 14:53
Thank you



20/8/2022 11:09、Connor Ryan ***@***.***>のメール:

﻿

Closed #6<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUQdeco2800%2F2022-ext-studio-1%2Fissues%2F6&data=05%7C01%7C%7Ca5fde57747b44d48d15608da82510b77%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637965581864848753%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BptQH%2B%2FsUxzgfgdd9pDU%2BfT5C%2FKXh92I%2Bmlh65Z7c6c%3D&reserved=0> as not planned.
